<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!--
    ================================= PROJECT INFO ==============================
    -->
    <groupId>umons.ac.be</groupId>
    <artifactId>visiblyrecursiveautomata</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>

    <name>Validation and Learning of Visibly Recursive Automata</name>

    <licenses>
        <!-- TODO -->
    </licenses>

    <developers>
        <!-- TODO -->
    </developers>

    <distributionManagement>
        <site>
            <id>apidoc</id>
            <url>file:${user.dir}/docs/api/</url>
        </site>
    </distributionManagement>

    <!--
    ================================= MODULES ===================================
    -->
    <modules>
        <module>vra</module>
        <module>learning</module>
        <module>automatalibvra</module>
        <module>jsonschemainference</module>
    </modules>


    <!--
    ================================= PROPERTIES ================================
    -->
    <properties>
        <!-- Global configuration -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.sourceEncoding>UTF-8</project.reporting.sourceEncoding>
        <maven.compiler.source>24</maven.compiler.source>
        <maven.compiler.target>24</maven.compiler.target>
        <maven.compiler.release>24</maven.compiler.release>

        <!-- Dependency versions -->
        <automatalib.version>0.12.0</automatalib.version>
        <learnlib.version>19.0.0</learnlib.version>
        <antlr.version>4.7.1</antlr.version>
        <jsonschematools.version>2.0</jsonschematools.version>
        <json.version>20231013</json.version>
    </properties>


    <!--
    ================================= DEPENDENCIES ==============================
    -->
    <dependencyManagement>
        <dependencies>
            <!-- Internal dependencies -->
            <dependency>
                <groupId>umons.ac.be</groupId>
                <artifactId>vra</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>umons.ac.be</groupId>
                <artifactId>automatalibvra</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- AutomataLib and LearnLib -->
            <dependency>
                <groupId>org.json</groupId>
                <artifactId>json</artifactId>
                <version>${json.version}</version>
            </dependency>
            <dependency>
                <groupId>net.automatalib.distribution</groupId>
                <artifactId>automata-distribution</artifactId>
                <version>${automatalib.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.learnlib.distribution</groupId>
                <artifactId>learnlib-distribution</artifactId>
                <version>${learnlib.version}</version>
                <type>pom</type>
            </dependency>

            <!-- Other dependencies -->
            <dependency>
                <groupId>org.antlr</groupId>
                <artifactId>antlr4-runtime</artifactId>
                <version>${antlr.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>be.ac.umons.jsonschematools</groupId>
                <artifactId>jsonschematools-core</artifactId>
                <version>${jsonschematools.version}</version>
            </dependency>
            <dependency>
                <groupId>be.ac.umons.jsonschematools</groupId>
                <artifactId>jsonschematools-validator</artifactId>
                <version>${jsonschematools.version}</version>
            </dependency>
            <dependency>
                <groupId>be.ac.umons.jsonschematools</groupId>
                <artifactId>jsonschematools-generator</artifactId>
                <version>${jsonschematools.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>